name: edikted
version: "1.0.0"
config-version: 2

profile: edikted

model-paths: ["models"]
target-path: "target"
clean-targets: ["target", "dbt_packages"]

models:
  edikted:
    staging:
      +schema: staging
      +materialized: view
    fact:
      +schema: fact
      +materialized: table
