version: 2

sources:
  - name: raw
    schema: raw
    tables:
      - name: edikted_112412
      - name: edikted_212412
      - name: edikted_212423
      - name: background_image
      - name: edikted_1sa112
      - name: edikted_1sa122
